### ISSUE TITLE
Streaming not working on rpi3

### ISSUE THREAD

**Issue by cara** [AmedeeBulle/octoprint-containers#1]
Unfortunately the streaming container is not working for me with rpi cam

> 25.11.18 19:01:31 (+0100)  webcam  MJPG-streamer [82]:        Perhaps you want to adjust the search path with:
> 25.11.18 19:01:31 (+0100)  webcam
> 25.11.18 19:01:31 (+0100)  webcam  MJPG-streamer [82]:        # export LD_LIBRARY_PATH=/path/to/plugin/folder
> 25.11.18 19:01:31 (+0100)  webcam
> 25.11.18 19:01:31 (+0100)  webcam  MJPG-streamer [82]:        dlopen: input_raspicam.so: cannot open shared object file: No such file or direct

input_raspicam.so fails to compile:
>  * PLUGIN_INPUT_RASPICAM , Raspberry Pi input camera plugin (unmet dependencies)

Tried to install varies dependencies, but had no success.
Would appreciate your help.
Thanks a lot!

**Comment by AmedeeBulle** [comment]
I will look at this, need to install a camera module on my test Raspberry

**Comment by AmedeeBulle** [comment]
Added `libraspberrypi-dev` package required for `input_raspicam`
Docker images have been updated.

**Comment by cara** [comment]
perfect, thank you very much!
