### ISSUE TITLE
Cant install telegram plugin

### ISSUE THREAD

**Issue by SpawW** [AmedeeBulle/octoprint-containers#2]
Hi, First all congrats for this very good octoprint container.

I install on a RaspPi 3 very easily, but when I try to install the **Telegram plugin**  (https://plugins.octoprint.org/plugins/telegram/) the installation process fail.

`

Installing plugin "OctoPrint-Telegram" from https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip.../opt/octoprint/OctoPrint/venv/bin/python -m pip install https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip --no-cache-dirLooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simpleCollecting https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zipDownloading https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zipRequirement already satisfied: OctoPrint in ./OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.3.10-py2.7.egg (from OctoPrint-Telegram==1.4.2) (1.3.10)Collecting pillow (from OctoPrint-Telegram==1.4.2)Downloading https://files.pythonhosted.org/packages/1b/e1/1118d60e9946e4e77872b69c58bc2f28448ec02c99a2ce456cd1a272c5fd/Pillow-5.3.0.tar.gz (15.6MB)Requirement already satisfied: flask<0.11,>=0.10.1 in ./OctoPrint/venv/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10.1)Requirement already satisfied: Jinja2<2.9,>=2.8.1 in ./OctoPrint/venv/lib/python2.7/site-packages/Jinja2-2.8.1-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.8.1)Requirement already satisfied: regex!=2018.11.6 in ./OctoPrint/venv/lib/python2.7/site-packages/regex-2018.11.22-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (2018.11.22)Requirement already satisfied: werkzeug<0.9,>=0.8.3 in ./OctoPrint/venv/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.8.3)Requirement already satisfied: tornado==4.5.3 in ./OctoPrint/venv/lib/python2.7/site-packages/tornado-4.5.3-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (4.5.3)Requirement already satisfied: PyYAML<3.11,>=3.10 in ./OctoPrint/venv/lib/python2.7/site-packages/PyYAML-3.10-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.10)Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in ./OctoPrint/venv/lib/python2.7/site-packages/Flask_Login-0.2.11-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.2.11)Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in ./OctoPrint/venv/lib/python2.7/site-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.3.5)Requirement already satisfied: Flask-Babel<0.10,>=0.9 in ./OctoPrint/venv/lib/python2.7/site-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.9)Requirement already satisfied: Flask-Assets<0.11,>=0.10 in ./OctoPrint/venv/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10)Requirement already satisfied: markdown<2.7,>=2.6.9 in ./OctoPrint/venv/lib/python2.7/site-packages/Markdown-2.6.11-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.11)Requirement already satisfied: pyserial<3.5,>=3.4 in ./OctoPrint/venv/lib/python2.7/site-packages/pyserial-3.4-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.4)Requirement already satisfied: netaddr<0.8,>=0.7.19 in ./OctoPrint/venv/lib/python2.7/site-packages/netaddr-0.7.19-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.7.19)Requirement already satisfied: watchdog<0.9,>=0.8.3 in ./OctoPrint/venv/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.8.3)Requirement already satisfied: sarge==0.1.5post0 in ./OctoPrint/venv/lib/python2.7/site-packages/sarge-0.1.5.post0-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.1.5.post0)Requirement already satisfied: netifaces<0.11,>=0.10.6 in ./OctoPrint/venv/lib/python2.7/site-packages/netifaces-0.10.7-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10.7)Requirement already satisfied: pylru<1.1,>=1.0.9 in ./OctoPrint/venv/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.0.9)Requirement already satisfied: rsa<3.3,>=3.2.3 in ./OctoPrint/venv/lib/python2.7/site-packages/rsa-3.2.3-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.2.3)Requirement already satisfied: pkginfo<1.5,>=1.4.2 in ./OctoPrint/venv/lib/python2.7/site-packages/pkginfo-1.4.2-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.4.2)Requirement already satisfied: requests<3,>=2.18.4 in ./OctoPrint/venv/lib/python2.7/site-packages/requests-2.21.0-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.21.0)Requirement already satisfied: semantic_version<2.5,>=2.4.2 in ./OctoPrint/venv/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.4.2)Requirement already satisfied: psutil<5.5,>=5.4.6 in ./OctoPrint/venv/lib/python2.7/site-packages/psutil-5.4.8-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (5.4.8)Requirement already satisfied: Click<6.3,>=6.2 in ./OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (6.2)Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in ./OctoPrint/venv/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.6.5)Requirement already satisfied: feedparser<5.3,>=5.2.1 in ./OctoPrint/venv/lib/python2.7/site-packages/feedparser-5.2.1-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (5.2.1)Requirement already satisfied: chainmap<1.1,>=1.0.2 in ./OctoPrint/venv/lib/python2.7/site-packages/chainmap-1.0.2-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.0.2)Requirement already satisfied: future<0.16,>=0.15.2 in ./OctoPrint/venv/lib/python2.7/site-packages/future-0.15.2-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.15.2)Requirement already satisfied: scandir<1.4,>=1.3 in ./OctoPrint/venv/lib/python2.7/site-packages/scandir-1.3-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)Requirement already satisfied: websocket-client<0.41,>=0.40.0 in ./OctoPrint/venv/lib/python2.7/site-packages/websocket_client-0.40.0-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.40.0)Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in ./OctoPrint/venv/lib/python2.7/site-packages/python_dateutil-2.6.1-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.1)Requirement already satisfied: wrapt<1.11,>=1.10.11 in ./OctoPrint/venv/lib/python2.7/site-packages/wrapt-1.10.11-py2.7-linux-armv7l.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.10.11)Requirement already satisfied: futures<3.2,>=3.1.1 in ./OctoPrint/venv/lib/python2.7/site-packages/futures-3.1.1-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.1.1)Requirement already satisfied: emoji<0.5,>=0.4.5 in ./OctoPrint/venv/lib/python2.7/site-packages/emoji-0.4.5-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.5)Requirement already satisfied: monotonic<1.4,>=1.3 in ./OctoPrint/venv/lib/python2.7/site-packages/monotonic-1.3-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)Requirement already satisfied: frozendict<1.3,>=1.2 in ./OctoPrint/venv/lib/python2.7/site-packages/frozendict-1.2-py2.7.egg (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.2)Requirement already satisfied: itsdangerous>=0.21 in ./OctoPrint/venv/lib/python2.7/site-packages/itsdangerous-1.1.0-py2.7.egg (from flask<0.11,>=0.10.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.1.0)Requirement already satisfied: MarkupSafe in ./OctoPrint/venv/lib/python2.7/site-packages/MarkupSafe-1.1.0-py2.7-linux-armv7l.egg (from Jinja2<2.9,>=2.8.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.1.0)Requirement already satisfied: singledispatch in ./OctoPrint/venv/lib/python2.7/site-packages/singledispatch-3.4.0.3-py2.7.egg (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (3.4.0.3)Requirement already satisfied: certifi in ./OctoPrint/venv/lib/python2.7/site-packages/certifi-2018.11.29-py2.7.egg (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (2018.11.29)Requirement already satisfied: backports_abc>=0.4 in ./OctoPrint/venv/lib/python2.7/site-packages/backports_abc-0.5-py2.7.egg (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.5)Requirement already satisfied: blinker in ./OctoPrint/venv/lib/python2.7/site-packages/blinker-1.4-py2.7.egg (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-Telegram==1.4.2) (1.4)Requirement already satisfied: Babel>=1.0 in ./OctoPrint/venv/lib/python2.7/site-packages/Babel-2.6.0-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.0)Requirement already satisfied: speaklater>=1.2 in ./OctoPrint/venv/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)Requirement already satisfied: webassets>=0.10 in ./OctoPrint/venv/lib/python2.7/site-packages/webassets-0.12.1-py2.7.egg (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-Telegram==1.4.2) (0.12.1)Requirement already satisfied: argh>=0.24.1 in ./OctoPrint/venv/lib/python2.7/site-packages/argh-0.26.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.26.2)Requirement already satisfied: pathtools>=0.1.1 in ./OctoPrint/venv/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.1.2)Requirement already satisfied: pyasn1>=0.1.3 in ./OctoPrint/venv/lib/python2.7/site-packages/pyasn1-0.4.4-py2.7.egg (from rsa<3.3,>=3.2.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.4)Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./OctoPrint/venv/lib/python2.7/site-packages/chardet-3.0.4-py2.7.egg (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (3.0.4)Requirement already satisfied: idna<2.9,>=2.5 in ./OctoPrint/venv/lib/python2.7/site-packages/idna-2.8-py2.7.egg (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (2.8)Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./OctoPrint/venv/lib/python2.7/site-packages/urllib3-1.24.1-py2.7.egg (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (1.24.1)Requirement already satisfied: Unidecode<0.05,>=0.04.14 in ./OctoPrint/venv/lib/python2.7/site-packages/Unidecode-0.4.21-py2.7.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.21)Requirement already satisfied: six in ./OctoPrint/venv/lib/python2.7/site-packages/six-1.12.0-py2.7.egg (from websocket-client<0.41,>=0.40.0->OctoPrint->OctoPrint-Telegram==1.4.2) (1.12.0)Requirement already satisfied: backports.ssl_match_hostname in ./OctoPrint/venv/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg (from websocket-client<0.41,>=0.40.0->OctoPrint->OctoPrint-Telegram==1.4.2) (3.5.0.1)Requirement already satisfied: pytz>=0a in ./OctoPrint/venv/lib/python2.7/site-packages/pytz-2018.7-py2.7.egg (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (2018.7)Installing collected packages: pillow, OctoPrint-TelegramRunning setup.py install for pillow: startedRunning setup.py install for pillow: finished with status 'error'Complete output from command /opt/octoprint/OctoPrint/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-LXtTqc/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4IFroF/install-record.txt --single-version-externally-managed --compile --install-headers /opt/octoprint/OctoPrint/venv/include/site/python2.7/pillow:running installrunning buildrunning build_pycreating buildcreating build/lib.linux-armv7l-2.7creating build/lib.linux-armv7l-2.7/PILcopying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/features.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PdfParser.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/__init__.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/_binary.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/_version.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/_util.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/Image.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PILcopying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PILrunning egg_infowriting src/Pillow.egg-info/PKG-INFOwriting top-level names to src/Pillow.egg-info/top_level.txtwriting dependency_links to src/Pillow.egg-info/dependency_links.txtreading manifest file 'src/Pillow.egg-info/SOURCES.txt'reading manifest template 'MANIFEST.in'warning: no files found matching '*.c'warning: no files found matching '*.h'warning: no files found matching '*.sh'no previously-included directories found matching 'docs/_static'warning: no previously-included files found matching '.appveyor.yml'warning: no previously-included files found matching '.coveragerc'warning: no previously-included files found matching '.codecov.yml'warning: no previously-included files found matching '.editorconfig'warning: no previously-included files found matching '.landscape.yaml'warning: no previously-included files found matching '.travis'warning: no previously-included files found matching '.travis/*'warning: no previously-included files found matching 'tox.ini'warning: no previously-included files matching '.git*' found anywhere in distributionwarning: no previously-included files matching '*.pyc' found anywhere in distributionwarning: no previously-included files matching '*.so' found anywhere in distributionwriting manifest file 'src/Pillow.egg-info/SOURCES.txt'running build_extThe headers or library files could not be found for zlib,a required dependency when compiling Pillow from source.Please see the install instructions at:https://pillow.readthedocs.io/en/latest/installation.htmlTraceback (most recent call last):File "<string>", line 1, in <module>File "/tmp/pip-install-LXtTqc/pillow/setup.py", line 814, in <module>raise RequiredDependencyException(msg)__main__.RequiredDependencyException:The headers or library files could not be found for zlib,a required dependency when compiling Pillow from source.Please see the install instructions at:https://pillow.readthedocs.io/en/latest/installation.html----------------------------------------Command "/opt/octoprint/OctoPrint/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-LXtTqc/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4IFroF/install-record.txt --single-version-externally-managed --compile --install-headers /opt/octoprint/OctoPrint/venv/include/site/python2.7/pillow" failed with error code 1 in /tmp/pip-install-LXtTqc/pillow/Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

`

**Comment by AmedeeBulle** [comment]
[Travis](https://travis-ci.org/AmedeeBulle/octoprint-containers/builds/471888944) has successfully re-built the containers and they are available on the [Docker Hub](https://hub.docker.com/r/amedee/octoprint-octoprint).

I can now successfully install `OctoPrint-Telegram` (didn't test the plugin itself)
