### ISSUE TITLE
haproxy is looping in balena 

### ISSUE THREAD

**Issue by nikil511** [AmedeeBulle/octoprint-containers#4]
haproxy is non-stop restarting on a clean install to rpi3
I am using a USB camera and have the env flags as per readme

**Comment by AmedeeBulle** [comment]
Any message of interest in the log console for the `haproxy` container?

**Comment by nikil511** [comment]
Not that I can see. See log attached.  Also build logs look normal for haproxy 
(however octoprint had python build errors)
How can I enable debug / see more detailed logs in haproxy?

[octoprint-amedeebulle_mk2-12.05.19_11_38_08_(+0300).txt](https://github.com/AmedeeBulle/octoprint-containers/files/3169894/octoprint-amedeebulle_mk2-12.05.19_11_38_08_.%2B0300.txt)

**Comment by AmedeeBulle** [comment]
Interresting: it is balena which decides to kill `haproxy`, not `haproxy` terminating by itself.

Can you double check that there is no spurious character in your variable names (typically a variable name which starts with a whitespace). I came across [this](https://forums.balena.io/t/service-stuck-in-endless-install-starting-killing-service-loop/4445/13) on the balena forum...

**Comment by nikil511** [comment]
I deleted env vars, tried without them, redid them, tried false/true . Does not seem to be related to the problem. 
Here are the diagnostics from balenacloud

[1a977f44b5ea407c2174baa72fbbbad6_13.05.2019_08_43_39+0000.txt](https://github.com/AmedeeBulle/octoprint-containers/files/3171939/1a977f44b5ea407c2174baa72fbbbad6_13.05.2019_08_43_39%2B0000.txt)

**Comment by AmedeeBulle** [comment]
I'll re-provision my device from scratch to see if I can reproduce...

**Comment by nikil511** [comment]
Thanks! 
btw, I asked for help from the balena forums, as I more curious on how to debug such a problem than fixing it ! :-)
https://forums.balena.io/t/haproxy-killing-loop/8236

**Comment by nikil511** [comment]
commenting out "EXPOSE 80 443" from haproxy Dockerfile.template fixed the problem!

**Comment by AmedeeBulle** [comment]
Thanks for the feedback.

I haven't re-image my device since quite some time, which explain why I don't have any issue with my old supervisor...

**Comment by AmedeeBulle** [comment]
For reference, this is the Balena issue: https://github.com/balena-io/balena-supervisor/issues/970
