### ISSUE TITLE
resin.io references should be balena.io

### ISSUE THREAD

**Issue by andrewnhem** [AmedeeBulle/octoprint-containers#7]
@AmedeeBulle -- thanks for making and maintaining this awesome project. Just so you're working with the most updated links/references/endpoints, please start using balena.io instead of resin.io.

If you want, I can push up changes to at least the readme to get things started. Let me know what you think! Thanks ahead.

**Comment by AmedeeBulle** [comment]
Yes, I recently updated the Dockerfiles to use the Balena images, and saw the old README...

If you get time before I do, PR is Welcome ;)
