### ISSUE TITLE
Server not starting on base of octoprint 1.4.2

### ISSUE THREAD

**Issue by asys3** [AmedeeBulle/octoprint-containers#8]
Hi,

I tried to rebuild the containers as described for octoprint 1.4.2 (latest)
There were several errors already in the build log, but at the end an image was created.
But the octoprint container doesn't start because of an error 
`  File "/opt/octoprint/OctoPrint/venv/local/lib/python2.7/site-packages/zipp-3.4.0-py2.7.egg/zipp.py", line 240
    def open(self, mode='r', *args, pwd=None, **kwargs):
                                      ^
SyntaxError: invalid syntax
`
Don't know what to do here?!

[serverstartlog.txt](https://github.com/AmedeeBulle/octoprint-containers/files/5516704/serverstartlog.txt)
[buildlog.txt](https://github.com/AmedeeBulle/octoprint-containers/files/5516706/buildlog.txt)
[docker-compose.txt](https://github.com/AmedeeBulle/octoprint-containers/files/5516722/docker-compose.txt)

Best regards,
Uwe

**Comment by AmedeeBulle** [comment]
Not sure what is happening here...
As Octoprint is now compatible with Python 3, I have updated the Dockerfiles to use Python 3.
I tested the build on 3 machines and it all works.

Let me know if this solves your issue.

**Comment by asys3** [comment]
Works like a charm! Container starts now and seems to be stable. UI responds.
Thanks a lot!
Is there a possibility to donate ?
Would like to give you a beer :-)

**Comment by AmedeeBulle** [comment]
Thanks for the for the feedback.
I'll appreciate a virtual beer ;)

Closing the issue
